### PR TITLE
Enable RStudio Connect API Key

### PR DESCRIPTION
**Pull request by akgold**
Related: https://github.com/rstudio/shinyloadtest/pull/133

### CODE REVIEW

**Review by schloerke — CHANGES_REQUESTED** [review]
Could also you remove the `shinycannon-1.1.0-*` files from the top level? Thank you!

**Comment by akgold** [comment]
@schloerke -- looks like most of these comments are addressed in #56. Anything here I should tune in on at this point?

**Comment by schloerke** [comment]
No. We can close this PR in favor of #56

**Comment by akgold** [comment]
👍 Thanks!

**Pull request closed without merging**
